version: "3.9"

services:
  api:
    build: .
    container_name: ecommerce_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
      - elasticsearch
      - kafka
    networks:
      - ecommerce_net
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    container_name: ecommerce_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ecommerce_net
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: ecommerce_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ecommerce_net
    restart: unless-stopped

  elasticsearch:
    image: elasticsearch:8.13.0
    container_name: ecommerce_es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - ecommerce_net
    restart: unless-stopped

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: ecommerce_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - ecommerce_net

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: ecommerce_kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - ecommerce_net
    restart: unless-stopped

  celery_worker:
    build: .
    container_name: ecommerce_celery
    command: celery -A app.tasks.email_tasks.celery_app worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
    networks:
      - ecommerce_net
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  es_data:

networks:
  ecommerce_net:
    driver: bridge
