name: Ecommerce Backend CI

on:

  push:
    branches:
      - master

  pull_request:

jobs:
  ecommerce-backend-ci:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Check Formatting (Black)
        run: |
          black --check .

      - name: Lint Code (Flake8)
        run: |
          flake8 .

      - name: Type Checking (Mypy)
        run: |
          mypy app

      - name: Security Scan (Bandit)
        run: |
          bandit -r app

      - name: Run Tests
        run: |
          pytest

      - name: Coverage Report
        run: |
          pytest --cov=app --cov-report=term-missing